"""One-seed, three-policy DoD/energy attribution evaluation.

Each policy receives the same deterministic 5,400-slot warm-up trajectory
generated by the gold BLA-MAPPO policy.  Formal evaluation then continues from
that warmed state for another 5,400 slots without an environment reset.

The output CSV has one row per algorithm, seed, satellite, and formal-evaluation
slot.  Plotting is delegated to ``plot_dod_energy_attribution.py`` so the CSV is
the sole input to all derived figures and metrics.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import random
import subprocess
import sys
import time
from pathlib import Path

import numpy as np
import torch

from core import Config, SatelliteMECEnv
from training import MAPPOPolicy


HERE = Path(__file__).resolve().parent
POLICIES = (
    ("w/o DoD", HERE / "checkpoints" / "MAPPO_NoBat_lh4_8K"),
    ("w/ Linear-DoD", HERE / "checkpoints" / "linear_dod_1seed_8k"),
    ("BLA-MAPPO", HERE / "checkpoints" / "LyaMAPPO_lh4_32K"),
)
CSV_FIELDS = (
    "algorithm", "seed", "scenario", "time_slot", "eval_slot", "satellite_id",
    "battery_start_j", "battery_capacity_j", "battery_end_j",
    "battery_counterfactual_j", "battery_counterfactual_physical_j",
    "solar_energy_j", "base_energy_j",
    "compute_energy_j", "tx_energy_j", "arrived_tasks", "completed_tasks",
    "ontime_tasks", "timeout_tasks", "rejected_tasks", "completed_bits",
    "completion_delay_sum_s",
)


class AttributionConfig(Config):
    """Match the repository's gold-checkpoint evaluation physics."""

    LAMBDA_HIGH = 4.0
    LAMBDA = 4.0 * Config.LAMBDA_HIGH_RATIO + Config.LAMBDA_LOW * (1 - Config.LAMBDA_HIGH_RATIO)
    KAPPA = 1.5e-27
    E_CAP = 54_000.0
    DOD_MIN = 0.0


def seed_everything(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    torch.use_deterministic_algorithms(True)


def load_policy(cfg: Config, name: str, checkpoint: Path) -> MAPPOPolicy:
    if not checkpoint.is_dir():
        raise FileNotFoundError(f"missing checkpoint: {checkpoint}")
    policy = MAPPOPolicy(cfg, name=name)
    policy.load(str(checkpoint))
    policy.set_eval_mode()
    return policy


def warmup_fingerprint(env: SatelliteMECEnv) -> str:
    """Hash the complete task/battery state needed to audit common warm-up."""
    sats = []
    for sat in env.constellation.satellites:
        def tasks(values):
            return [
                (t.task_id, t.current_sat, t.status, t.processed, t.hops, t.trans_delay_acc)
                for t in values
            ]

        sats.append({
            "id": sat.sat_id,
            "dod": sat.dod,
            "z": sat.z,
            "qf": tasks(sat.forward_queue),
            "qb": tasks(sat.compute_queue),
            "alpha": sat.alpha_bar,
        })
    state = {
        "slot": env.current_slot,
        "sats": sats,
        "rng_task": env.constellation.rng_task.bit_generator.state,
        "rng_param": env.constellation.rng_task_param.bit_generator.state,
    }
    payload = json.dumps(state, sort_keys=True, separators=(",", ":"), default=str)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def write_slot_rows(writer: csv.DictWriter, algorithm: str, seed: int,
                    scenario: str, eval_slot: int, info: dict, cfg: Config) -> None:
    arrays = {
        "battery_start_j": info["per_sat_battery_start_j"],
        "battery_end_j": info["per_sat_battery_end_j"],
        "battery_counterfactual_j": info["per_sat_battery_counterfactual_j"],
        "battery_counterfactual_physical_j": info[
            "per_sat_battery_counterfactual_physical_j"
        ],
        "solar_energy_j": info["per_sat_solar_energy_j"],
        "base_energy_j": info["per_sat_base_energy_j"],
        "compute_energy_j": info["per_sat_compute_energy_j"],
        "tx_energy_j": info["per_sat_tx_energy_j"],
        "arrived_tasks": info["per_sat_arrived"],
        "completed_tasks": info["per_sat_completed"],
        "ontime_tasks": info["per_sat_ontime"],
        "timeout_tasks": info["per_sat_timeout"],
        "rejected_tasks": info["per_sat_rejected"],
        "completed_bits": info["per_sat_completed_bits"],
        "completion_delay_sum_s": info["per_sat_delay_sum"],
    }
    for key, values in arrays.items():
        if len(values) != cfg.N_SATS:
            raise ValueError(f"{key} has {len(values)} values, expected {cfg.N_SATS}")
    for n in range(cfg.N_SATS):
        writer.writerow({
            "algorithm": algorithm,
            "seed": seed,
            "scenario": scenario,
            "time_slot": info["slot"],
            "eval_slot": eval_slot,
            "satellite_id": n,
            "battery_start_j": arrays["battery_start_j"][n],
            "battery_capacity_j": cfg.E_CAP,
            "battery_end_j": arrays["battery_end_j"][n],
            "battery_counterfactual_j": arrays["battery_counterfactual_j"][n],
            "battery_counterfactual_physical_j": arrays[
                "battery_counterfactual_physical_j"
            ][n],
            "solar_energy_j": arrays["solar_energy_j"][n],
            "base_energy_j": arrays["base_energy_j"][n],
            "compute_energy_j": arrays["compute_energy_j"][n],
            "tx_energy_j": arrays["tx_energy_j"][n],
            "arrived_tasks": arrays["arrived_tasks"][n],
            "completed_tasks": arrays["completed_tasks"][n],
            "ontime_tasks": arrays["ontime_tasks"][n],
            "timeout_tasks": arrays["timeout_tasks"][n],
            "rejected_tasks": arrays["rejected_tasks"][n],
            "completed_bits": arrays["completed_bits"][n],
            "completion_delay_sum_s": arrays["completion_delay_sum_s"][n],
        })


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--warmup-slots", type=int, default=5_400)
    parser.add_argument("--eval-slots", type=int, default=5_400)
    parser.add_argument(
        "--output-dir", type=Path,
        default=HERE / "results" / "dod_energy_attribution_seed42",
    )
    parser.add_argument("--skip-plots", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    seed_everything(args.seed)
    output = args.output_dir.resolve()
    output.mkdir(parents=True, exist_ok=True)
    csv_path = output / "satellite_slot_metrics.csv"
    scenario = "lambda_high_4_shared_gold_warmup"

    cfg = AttributionConfig()
    cfg.SEED = args.seed
    cfg.SEED_TASK = args.seed
    cfg.SEED_TASK_PARAM = args.seed + 1
    cfg.SEED_LINK = args.seed + 2
    cfg.SEED_NET = args.seed + 3
    cfg.SEED_TRAIN = args.seed + 4
    cfg.T_WARMUP = args.warmup_slots
    cfg.T_EVAL = args.eval_slots
    cfg.T_TOTAL = args.warmup_slots + args.eval_slots + cfg.ORBIT_PERIOD
    cfg.N_EVAL_RUNS = 1
    cfg.V_DVFS = 2e17
    cfg.LINEAR_DOD_LOSS = False  # all algorithms measured with the same convex lifetime model
    eval_seeds = {
        "task": args.seed + 100,
        "task_param": args.seed + 101,
        "dod_init": args.seed + 102,
    }

    fingerprints: dict[str, str] = {}
    started = time.time()
    with csv_path.open("w", newline="", encoding="utf-8") as stream:
        writer = csv.DictWriter(stream, fieldnames=CSV_FIELDS)
        writer.writeheader()
        for algorithm, checkpoint in POLICIES:
            # Fresh objects ensure no recurrent/transient state crosses methods.
            env = SatelliteMECEnv(cfg)
            gold = load_policy(cfg, "gold-warmup", POLICIES[-1][1])
            candidate = gold if algorithm == "BLA-MAPPO" else load_policy(cfg, algorithm, checkpoint)
            env.reset(phase="warmup", seeds=eval_seeds)

            for t in range(args.warmup_slots):
                env.step(policy=gold)
                if (t + 1) % 900 == 0:
                    print(f"[{algorithm}] gold warm-up {t + 1}/{args.warmup_slots}", flush=True)

            fingerprints[algorithm] = warmup_fingerprint(env)
            if len(set(fingerprints.values())) != 1:
                raise RuntimeError(f"common warm-up mismatch: {fingerprints}")

            env.begin_evaluation_from_current_state()
            candidate.set_eval_mode()
            for eval_slot in range(args.eval_slots):
                _, _, _, info = env.step(policy=candidate)
                write_slot_rows(writer, algorithm, args.seed, scenario, eval_slot, info, cfg)
                if (eval_slot + 1) % 900 == 0:
                    print(f"[{algorithm}] formal eval {eval_slot + 1}/{args.eval_slots}", flush=True)

    expected_rows = len(POLICIES) * cfg.N_SATS * args.eval_slots
    manifest = {
        "data_granularity": "algorithm x seed x satellite x slot",
        "algorithms": [name for name, _ in POLICIES],
        "seed": args.seed,
        "scenario": scenario,
        "n_satellites": cfg.N_SATS,
        "warmup_policy": "BLA-MAPPO (gold LyaMAPPO_lh4_32K)",
        "warmup_slots": args.warmup_slots,
        "formal_eval_slots": args.eval_slots,
        "expected_csv_rows": expected_rows,
        "warmup_fingerprint": next(iter(fingerprints.values())),
        "common_warmup_verified": len(set(fingerprints.values())) == 1,
        "checkpoints": {name: str(path.relative_to(HERE)) for name, path in POLICIES},
        "physics": {
            "battery_capacity_j": cfg.E_CAP,
            "kappa": cfg.KAPPA,
            "v_dvfs": cfg.V_DVFS,
            "dod_min": cfg.DOD_MIN,
            "dod_max": cfg.DOD_MAX,
            "a_coefficient": cfg.A_COEF,
            "lambda_high": cfg.LAMBDA_HIGH,
        },
        "elapsed_s_before_plotting": time.time() - started,
    }
    (output / "run_manifest.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    print(f"CSV complete: {expected_rows} rows -> {csv_path}", flush=True)

    if not args.skip_plots:
        subprocess.run(
            [sys.executable, str(HERE / "plot_dod_energy_attribution.py"),
             "--csv", str(csv_path), "--output-dir", str(output / "figures")],
            check=True,
        )


if __name__ == "__main__":
    main()
